# 25/11/2021

- image   : sebastien-deleersnyder.jpg
  day     :
  time    :
  name    : Sebastien Deleersnyder
  bio     : >-
            Seba (<a href="https://twitter.com/Sebadele">https://twitter.com/Sebadele</a>)  is co-founder, CTO of Toreon and a proponent of application security as a holistic endeavor. He started the Belgian OWASP chapter, was a member of the OWASP Foundation Board and performed several public presentations on Application Security. Seba also co-organized the yearly security & hacker BruCON conference and trainings in Belgium.<br />
            With a background in development and many years of experience in security, he has trained countless developers to create software more securely. He has led OWASP projects such as OWASP SAMM, thereby truly making the world a little bit safer. Now he is adapting application security models to the evolving field of DevOps and is also focused on bringing Threat Modeling to a wider audience.
  title   : OWASP SAMM
  abstract: >-
            Building security into the software development and management practices of an organisation can be a daunting task. There are many factors that must be considered when charting your path forward, inlcuding&#58; company structure, stakeholder priorities, technology stacks, tools and processes, and existing technical debt.<br />
            <br />
            Implementing software assurance can produce significant benefits for the organisation. However, trying to achieve this without a good framework often yields only marginal and unsustainable improvements. OWASP SAMM (<a href="https://owaspsamm.org/">https://owaspsamm.org/</a>) provides exactly the structured, measurable framework that's needed. It enables you to formulate and implement a strategy for software security tailored to your organisation's risk profile.<br />
            <br />
            This one-day training is organised as a mix of presentations and interactive workshops. Our goal is for participants to get an in-depth view of, and practical feel for, the OWASP SAMM model. The session is organised in three parts&#58;<br />
            <ul>
            <li>First, we present an overview of the model and review the similarities and differences with other models. The five Business Functions - Governance, Design, Implementation, Verification, and Operations - are explained. We address the various constituent elements (e.g., metrics), review representative usage scenarios for the model, and defining an assessment's scope.</li>
            <li>The majority of our day will be spent reviewing the Security Practices comprising each Business Function, with an emphasis on assessing your organisation's maturity. Each Practice's treatment will include a hands-on segment, providing you an opportunity to apply SAMM to your organisation (or one you have worked for). We will assess representative Activities across all SAMM Practices, discussing our results and concerns in the group. This will give participants a good indication of their organisations’ maturity in software assurance. In the same effort, we will define a target model for your organisation and identify the most important challenges in getting there.</li>
            <li>The final part of the training will be dedicated to specific questions or challenges that you are facing about secure development in your organisation. In this group discussion, experiences will be shared among participants to address these questions.</li>
            </ul>
            If you've been struggling to launch a secure software initiative in your organisation, this training should provide you with the necessary foundations and ideas to do so.<br />
            <br />
            SAMM training outline<br />
            <ul>
            <li>Introductions and Class Overview</li>
            <li>The "Application Security Problem"</li>
            <li>Software Development Lifecycle (SDLC) Overview</li>
            <li>SAMM - Vision, History, Structure</li>
            <li>SAMM as an Assessment Tool</li>
            <li>Establishing Assessment Scope</li>
            <li>Methodology - Assessment and Roadmapping</li>
            <li>Assessing Governance
              <ul>
                  <li>Strategy & Metrics</li>
                  <li>Policy & Compliance</li>
                  <li>Education & Guidance</li>
              </ul>
            </li>
            <li>Assessing Design
              <ul>
                  <li>Threat Assessment</li>
                  <li>Security Requirements</li>
                  <li>Security Architecture</li>
              </ul>
            </li>
            <li>Assessing Implementation
              <ul>
                  <li>Secure Build</li>
                  <li>Secure Deployment</li>
                  <li>Defect Management</li>
              </ul>
            </li>
            <li>Assessing Verification
              <ul>
                  <li>Architecture Assessment</li>
                  <li>Requirements-driven Testing</li>
                  <li>Security Testing</li>
              </ul>
            </li>
            <li>Assessing Operations
              <ul>
                  <li>Incident Management</li>
                  <li>Environment Management</li>
                  <li>Operational Management</li>
              </ul>
            </li>
            <li>Setting Improvement Targets</li>
            <li>OWASP SAMM Tools
              <ul>
                  <li>Assessment Toolkit</li>
                  <li>SAMMwise</li>
                  <li>SAMM Benchmark Project</li>
                  <li>Integration with Other OWASP Projects & Tools</li>
              </ul>
            </li>
            <li>SAMM Best Practices
              <ul>
                  <li>Choosing the Right Starting Points</li>
                  <li>Monitoring and Metrics</li>
                  <li>Achieving Security by Default</li>
                  <li>Critical Success Factors</li>
              </ul>
            </li>
            <li>Wrap-up
              <ul>
                <li>Conclusions</li>
                <li>Looking Forward</li>
                <li>Getting Involved</li>
              </ul>
            </li>
            </ul>
  feed    : 
  url     : 
  urltag  : 

- image   : glenn-ten-cate.jpg
  day     :
  time    :
  name    : Glenn ten Cate
  bio     : >-
            As a coder, hacker, speaker, trainer and security chapter leader employed at ING Belgium Glenn has over 15 years experience in the field of security.<br />
            One of the founders of defensive development security trainings dedicated to helping you build and maintain secure software and also speaking at multiple other security conferences in the world.<br />
            <br />
            Not only does Glenn train developers, he and his brother Riccardo also donated an entire knowledge framework solely dedicated to help developers make their code secure by design.<br />
            <br />
            See&#58;<br />
            SKF (Security knowledge framework) <a href="https://www.securityknowledgeframework.org">https://www.securityknowledgeframework.org</a>
  title   : SKF Workshop - Offensive and Defensive crash course using SKF Labs
  abstract: >-
            Practice-changing impact, long lasting security knowledge and skills -- are the expected outcomes of this new-school webapp security training. This is a training with minimum lectures and all focused on hands-on exercises. We start off with some understanding of secure development and the secure coding principles. Then we do basic hacking challenges and move gradually to the advanced topics, but after that we do exercises that are about fixing vulnerable code. The attendees will have after this course a vast set of actionable knowledge and practise to be used straight away.<br /> 
            <br />
            Below is the main agenda overview that will be used as a structure but we will, based on the audience, select other topics of interest that we will do on this training day.<br />
            The full list of labs we 'can' do is found here: <a href="https://github.com/blabla1337/skf-labs">https://github.com/blabla1337/skf-labs</a><br />
            <br />
            <b>SKF Training outline</b><br />
            <br />
            Introduction to vulnerabilities<br />
            Intro to secure coding<br />
            OWASP ASVS topics, an introduction to the areas to protect<br />
            How a properly designed infrastructure architecture should be built<br />
            Intro to practical secure development<br />
            Code security<br />
            Server-side defense<br />
            Input validation vs encoding<br />
            Common server-side vulnerabilities and their defense<br />
            <ul>
              <li>Injections&#58; SQLi, XML injections, JSON, XPath, XSS, cookie injection, open redirection, http header injection</li>
              <li>Path traversal, XXE, RFI, Insecure file upload, Code execution</li>
              <li>Insecure direct object reference</li>
            </ul>
            Common client-side vulnerabilities and their defense<br />
            <ul>
              <li>XSS (types, impact, causes, defenses, other html injections, BeEF)</li>
              <li>CSRF, Clickjacking, Same-origin policy, CORS</li>
            </ul>
            And many more! Join us and don't miss this opportunity to learn offensive & defensive practical hands-on experience.<br />
            You only need to bring your laptop and internet access to follow this training.
  feed    : 
  url     : 
  urltag  : 
